### ISSUE TITLE
Add "Please Validate" Screen

### ISSUE THREAD

**Issue by malcscott91** [FordLabs/PeopleMover#81]
# Feature Request

## Context
In the current state, when a user is initially signing up for PeopleMover it is unclear that they are required to verify their email upon entering their information. We need another screen that communicates the verification.

## Story
**As a** People Allocator 
**I want** know that I need to verify my email
**So** that I can have access to PeopleMover

----

## Acceptance Criteria
**Given** I am signing up to use PeopleMover for the first time
**When** I enter my information (name, email, etc.)
**Then** I can clearly see that I need to verify my email address before getting access

## Design
**Verify Email Screen:** https://www.figma.com/file/S4XKeovlQqeRk64k2qzhf8gL/PeopleMover?node-id=2891%3A788

**Comment by jshaddac** [comment]
I think we were adjusting colors with the other story right? So I shouldn't comment on the header being black instead of purple? 

Other than that, can we bold the link and add a period at the end since there is a comma int he middle. 

The spacing is also a bit off and loose. We don't necessarily need to spend our time totally refining it right now, but if it's realatively quick, the app will feel better if the look is consistent.

**Comment by jshaddac** [comment]
I put the above in as Solo stories and I'm moving this along!
